/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: WbcReference.idl
  Source: WbcReference.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_WBCREFERENCE_HPP
#define DDSCXX_WBCREFERENCE_HPP

#include <cstdint>
#include <vector>
#include <string>

namespace wbc_g1_deploy
{
namespace msg
{
namespace dds_
{
class MetaKV_
{
private:
 std::string name_;
 std::vector<float> values_;

public:
  MetaKV_() = default;

  explicit MetaKV_(
    const std::string& name,
    const std::vector<float>& values) :
    name_(name),
    values_(values) { }

  const std::string& name() const { return this->name_; }
  std::string& name() { return this->name_; }
  void name(const std::string& _val_) { this->name_ = _val_; }
  void name(std::string&& _val_) { this->name_ = _val_; }
  const std::vector<float>& values() const { return this->values_; }
  std::vector<float>& values() { return this->values_; }
  void values(const std::vector<float>& _val_) { this->values_ = _val_; }
  void values(std::vector<float>&& _val_) { this->values_ = _val_; }

  bool operator==(const MetaKV_& _other) const
  {
    (void) _other;
    return name_ == _other.name_ &&
      values_ == _other.values_;
  }

  bool operator!=(const MetaKV_& _other) const
  {
    return !(*this == _other);
  }

};

class WbcReference_
{
private:
 uint32_t version_ = 0;
 std::string schema_;
 std::string mode_;
 std::string robot_id_;
 uint64_t stamp_us_ = 0;
 uint64_t step_ = 0;
 std::vector<::wbc_g1_deploy::msg::dds_::MetaKV_> meta_;
 std::vector<float> arc_;
 std::vector<float> joint_pos_;

public:
  WbcReference_() = default;

  explicit WbcReference_(
    uint32_t version,
    const std::string& schema,
    const std::string& mode,
    const std::string& robot_id,
    uint64_t stamp_us,
    uint64_t step,
    const std::vector<::wbc_g1_deploy::msg::dds_::MetaKV_>& meta,
    const std::vector<float>& arc,
    const std::vector<float>& joint_pos) :
    version_(version),
    schema_(schema),
    mode_(mode),
    robot_id_(robot_id),
    stamp_us_(stamp_us),
    step_(step),
    meta_(meta),
    arc_(arc),
    joint_pos_(joint_pos) { }

  uint32_t version() const { return this->version_; }
  uint32_t& version() { return this->version_; }
  void version(uint32_t _val_) { this->version_ = _val_; }
  const std::string& schema() const { return this->schema_; }
  std::string& schema() { return this->schema_; }
  void schema(const std::string& _val_) { this->schema_ = _val_; }
  void schema(std::string&& _val_) { this->schema_ = _val_; }
  const std::string& mode() const { return this->mode_; }
  std::string& mode() { return this->mode_; }
  void mode(const std::string& _val_) { this->mode_ = _val_; }
  void mode(std::string&& _val_) { this->mode_ = _val_; }
  const std::string& robot_id() const { return this->robot_id_; }
  std::string& robot_id() { return this->robot_id_; }
  void robot_id(const std::string& _val_) { this->robot_id_ = _val_; }
  void robot_id(std::string&& _val_) { this->robot_id_ = _val_; }
  uint64_t stamp_us() const { return this->stamp_us_; }
  uint64_t& stamp_us() { return this->stamp_us_; }
  void stamp_us(uint64_t _val_) { this->stamp_us_ = _val_; }
  uint64_t step() const { return this->step_; }
  uint64_t& step() { return this->step_; }
  void step(uint64_t _val_) { this->step_ = _val_; }
  const std::vector<::wbc_g1_deploy::msg::dds_::MetaKV_>& meta() const { return this->meta_; }
  std::vector<::wbc_g1_deploy::msg::dds_::MetaKV_>& meta() { return this->meta_; }
  void meta(const std::vector<::wbc_g1_deploy::msg::dds_::MetaKV_>& _val_) { this->meta_ = _val_; }
  void meta(std::vector<::wbc_g1_deploy::msg::dds_::MetaKV_>&& _val_) { this->meta_ = _val_; }
  const std::vector<float>& arc() const { return this->arc_; }
  std::vector<float>& arc() { return this->arc_; }
  void arc(const std::vector<float>& _val_) { this->arc_ = _val_; }
  void arc(std::vector<float>&& _val_) { this->arc_ = _val_; }
  const std::vector<float>& joint_pos() const { return this->joint_pos_; }
  std::vector<float>& joint_pos() { return this->joint_pos_; }
  void joint_pos(const std::vector<float>& _val_) { this->joint_pos_ = _val_; }
  void joint_pos(std::vector<float>&& _val_) { this->joint_pos_ = _val_; }

  bool operator==(const WbcReference_& _other) const
  {
    (void) _other;
    return version_ == _other.version_ &&
      schema_ == _other.schema_ &&
      mode_ == _other.mode_ &&
      robot_id_ == _other.robot_id_ &&
      stamp_us_ == _other.stamp_us_ &&
      step_ == _other.step_ &&
      meta_ == _other.meta_ &&
      arc_ == _other.arc_ &&
      joint_pos_ == _other.joint_pos_;
  }

  bool operator!=(const WbcReference_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::wbc_g1_deploy::msg::dds_::MetaKV_>::getTypeName()
{
  return "wbc_g1_deploy::msg::dds_::MetaKV_";
}

template <> constexpr bool TopicTraits<::wbc_g1_deploy::msg::dds_::MetaKV_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::wbc_g1_deploy::msg::dds_::MetaKV_>::isKeyless()
{
  return true;
}

template <> constexpr const char* TopicTraits<::wbc_g1_deploy::msg::dds_::WbcReference_>::getTypeName()
{
  return "wbc_g1_deploy::msg::dds_::WbcReference_";
}

template <> constexpr bool TopicTraits<::wbc_g1_deploy::msg::dds_::WbcReference_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::wbc_g1_deploy::msg::dds_::WbcReference_>::isKeyless()
{
  return true;
}

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::wbc_g1_deploy::msg::dds_::MetaKV_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::wbc_g1_deploy::msg::dds_::MetaKV_>::getTypeName();
    }
};

template <>
struct topic_type_name<::wbc_g1_deploy::msg::dds_::WbcReference_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::wbc_g1_deploy::msg::dds_::WbcReference_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::wbc_g1_deploy::msg::dds_::MetaKV_)
REGISTER_TOPIC_TYPE(::wbc_g1_deploy::msg::dds_::WbcReference_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::wbc_g1_deploy::msg::dds_::MetaKV_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::wbc_g1_deploy::msg::dds_::MetaKV_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.name(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.values().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.values()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::wbc_g1_deploy::msg::dds_::MetaKV_& instance, bool as_key) {
  auto &props = get_type_props<::wbc_g1_deploy::msg::dds_::MetaKV_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::wbc_g1_deploy::msg::dds_::MetaKV_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.name(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.values().size());
      if (!read(streamer, se_1))
        return false;
      instance.values().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.values()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::wbc_g1_deploy::msg::dds_::MetaKV_& instance, bool as_key) {
  auto &props = get_type_props<::wbc_g1_deploy::msg::dds_::MetaKV_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::wbc_g1_deploy::msg::dds_::MetaKV_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.name(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.values().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::wbc_g1_deploy::msg::dds_::MetaKV_& instance, bool as_key) {
  auto &props = get_type_props<::wbc_g1_deploy::msg::dds_::MetaKV_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::wbc_g1_deploy::msg::dds_::MetaKV_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.name(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::wbc_g1_deploy::msg::dds_::MetaKV_& instance, bool as_key) {
  auto &props = get_type_props<::wbc_g1_deploy::msg::dds_::MetaKV_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

template<>
propvec &get_type_props<::wbc_g1_deploy::msg::dds_::WbcReference_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::wbc_g1_deploy::msg::dds_::WbcReference_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.version()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.schema(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.mode(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.robot_id(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.stamp_us()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.step()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.meta().size());
      if (!write(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!write(streamer, instance.meta()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.arc().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.arc()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_pos().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.joint_pos()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::wbc_g1_deploy::msg::dds_::WbcReference_& instance, bool as_key) {
  auto &props = get_type_props<::wbc_g1_deploy::msg::dds_::WbcReference_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::wbc_g1_deploy::msg::dds_::WbcReference_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.version()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.schema(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.mode(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.robot_id(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.stamp_us()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.step()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.meta().size());
      if (!read(streamer, se_1))
        return false;
      instance.meta().resize(se_1);
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!read(streamer, instance.meta()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.arc().size());
      if (!read(streamer, se_1))
        return false;
      instance.arc().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.arc()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_pos().size());
      if (!read(streamer, se_1))
        return false;
      instance.joint_pos().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.joint_pos()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::wbc_g1_deploy::msg::dds_::WbcReference_& instance, bool as_key) {
  auto &props = get_type_props<::wbc_g1_deploy::msg::dds_::WbcReference_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::wbc_g1_deploy::msg::dds_::WbcReference_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.version()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.schema(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.mode(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.robot_id(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.stamp_us()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.step()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.meta().size());
      if (!move(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!move(streamer, instance.meta()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.arc().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_pos().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::wbc_g1_deploy::msg::dds_::WbcReference_& instance, bool as_key) {
  auto &props = get_type_props<::wbc_g1_deploy::msg::dds_::WbcReference_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::wbc_g1_deploy::msg::dds_::WbcReference_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.version()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.schema(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.mode(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.robot_id(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.stamp_us()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.step()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!max(streamer, instance.meta()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::wbc_g1_deploy::msg::dds_::WbcReference_& instance, bool as_key) {
  auto &props = get_type_props<::wbc_g1_deploy::msg::dds_::WbcReference_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_WBCREFERENCE_HPP
